### ISSUE TITLE
BUG: TXT created with CNAME

### ISSUE THREAD

**Issue by kuritka** [AbsaOSS/external-dns-infoblox-webhook#23]
```yaml
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: test-01
spec:
  endpoints:
  - dnsName: cname-test.foo.example.com
    recordType: CNAME
    recordTTL: 30
    targets:
    - cname-test.blah.example.com
```
log says: `level=debug msg="requesting apply changes, create: 3 , updateOld: 0, updateNew: 0, delete: 0" requestMethod=POST requestPath=/records ` and `msg="Changing record" action=CREATE record=cname-test.foo.example.com target="heritage=external-dns,external-dns/owner=..." ttl=0 type=RecordTXT `

CreateObject request error: 'WAPI request error: 400('400 Bad Request'

for such DNS endpoint it creates CNAME and TXT record.  CNAME is created while TXT fails.  

- investigate issue
- consider whether TXT needs to be created
